crystalcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
]

main_app/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('crystals/', views.crystals_index, name='index'),
    path('crystals/<int:crystal_id>/', views.crystals_detail, name='detail'),
    path('cats/<int:crystal_id>/add_cleansing/', views.add_cleansing, name='add_cleansing'),
    path('crystals/<int:crystal_id>/assoc_energy/<int:energy_id>/',views.assoc_energy, name='assoc_energy'),
    path('crystals/create/', views.CrystalCreate.as_view(), name='crystals_create'),
    path('crystals/<int:pk>/update/', views.CrystalUpdate.as_view(), name='crystals_update'),
    path('crystals/<int:pk>/delete/', views.CrystalDelete.as_view(), name='crystals_delete'),
    path('energys/', views.EnergyList.as_view(), name='energys_index'),
    path('energys/<int:pk>/', views.EnergyDetail.as_view(), name='energys_detail'),
    path('energys/<int:pk>/update/', views.EnergyUpdate.as_view(), name='energys_update'),
    path('energys/<int:pk>/delete/', views.EnergyDelete.as_view(), name='energys_delete'),
    path('energys/create/', views.EnergyCreate.as_view(), name='energys_create'),
    
    ]

main_app/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
CLEANSE =(
    ('S', 'SUNLIGHT'),
    ('D', 'MOONLIGHT'),
    ('H','HELD')
)

class Energy(models.Model):
    wellness = models.CharField(max_length=50)
    meaning = models.CharField(max_length=50)
    

    def __str__(self):
        return f"harnesses {self.wellness}properties, and means {self.meaning}"

class Crystal(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    color = models.CharField(max_length=100)
    energys = models.ManyToManyField(Energy)
   
 
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('detail', kwargs={ 'crystal_id': self.id })

class Cleansing(models.Model):
    date = models.DateField('cleansing date')
    cleanse = models.CharField(
        max_length=1,
            choices=CLEANSE,
            default=CLEANSE[0][0]
    )
    crystal = models.ForeignKey(Crystal, on_delete=models.CASCADE)


    def __str__(self):
        return f"{self.get_cleanse_display()} on {self.date}"

    class Meta:
        ordering = ['-date']    

main_app/forms.py
from django.forms import ModelForm
from.models import Cleansing

class CleansingForm(ModelForm):
    class Meta:
        model = Cleansing
        fields = ['date', 'cleanse']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView

from .models import Crystal, Energy
from .forms import CleansingForm


        
def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

def crystals_index(request):
    crystals = Crystal.objects.all()
    return render(request, 'crystals/index.html', {'crystals': crystals })

def crystals_detail(request, crystal_id):
    crystal = Crystal.objects.get(id=crystal_id)
    cleansing_form = CleansingForm()

    energys_crystal_doesnt_have = Energy.objects.exclude(id__in = crystal.energys.all().values_list('id'))
    
    return render(request, 'crystals/detail.html', {
        'crystal': crystal, 
        'cleansing_form': cleansing_form,
        'energys': energys_crystal_doesnt_have
        }
    )
def add_cleansing(request, crystal_id):
    form = CleansingForm(request.POST)
    if form.is_valid():
        new_cleansing = form.save(commit=False)
        new_cleansing.crystal_id = crystal_id
        new_cleansing.save()
    return redirect('detail', crystal_id=crystal_id)

def assoc_energy(request, crystal_id, energy_id):
    Crystal.objects.get(id=crystal_id).energys.add(energy_id)
    return redirect('detail', crystal_id= crystal_id)

class CrystalCreate(CreateView):
    model = Crystal
    fields = '__all__'
   
class CrystalUpdate(UpdateView):
    model = Crystal 
    fields = ['description', 'properties', 'color']  

class CrystalDelete(DeleteView):
    model = Crystal
    success_url = '/crystals/'

class EnergyList(ListView):
    model = Energy

class EnergyDetail(DetailView):
    model = Energy

class EnergyCreate(CreateView):
    model = Energy
    fields = "__all__"
    success_url = '/energys/'

class EnergyUpdate(UpdateView):
    model = Energy
    fields = "__all__"
    success_url = '/energys/'

class EnergyDelete(DeleteView):
    model = Energy
    success_url = '/energys/'

main_app/templates/about.html
    {% extends 'base.html' %}
    {% block content %}

    <h1> About Crystal Collector</h1>
    <hr />
    <p> Hire the Crystal Collector!</p>
    {% endblock %}
    

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Crystal Collector</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <ul>
          <li><a href="/" class="left brand-logo">&nbsp;&nbsp;Crystal Collector</a></li>
        </ul>
        <ul class="right">
          <li><a href="{% url 'about' %}">About</a></li>
          <li><a href= "{% url 'crystals_create' %}">Add a Crystal</a></li>
          <li><a href="{% url 'index' %}"> View All Our Crystals</a></li>
          <li><a href="{% url 'energys_create' %}">Add an Energy</a></li>

        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}

    {% endblock %}
  </main>
  <footer class="page-footer">
    <div class="right">All Rights Reserved, &copy; 2020 Crystal Collector &nbsp;</div>
  </footer>
</body>
</html>

main_app/templates/crystals/detail.html
{% extends 'base.html' %}

{% block content %}
<h1>Crystal Details</h1>

<div class="row">
    <div class="col s6">
      <div class="card">
        <div class="card-content">
        <span class="card-title">{{ crystal.name }}</span>
         <p>Name: {{ crystal.name }}</p>
         <p>Description: {{ crystal.description }}</p>
            <p> Color: {{crystal.color }}</p>
            </div>
            <div class="card-action">
            <a href="{% url 'crystals_update' crystal.id %}">Edit</a>
            <a href="{% url 'crystals_delete' crystal.id %}">Delete</a>
            </div>
        </div>
    </div>
  <div class="col s6">
    <form action="{% url 'add_cleansing' crystal.id %}" method= "post">
        {% csrf_token %}
        {{ cleansing_form.as_p }}
        <input type="submit" class="btn" value="Add Cleansing">
    </form>
    <table class="striped">
      <thead>
        <tr><th>Date</th><th>Cleanse</th></tr>
      </thead>
      <tbody>
        {% for cleansing in crystal.cleansing_set.all %}
          <tr>
            <td>{{cleansing.date}}</td>
            <td>{{cleansing.get_cleanse_display}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
<hr>
<div class="row">
 <div class="col s6">
  <h3>{{ crystal.name }}'s Energys</h3>
  {% if crystal.energys.count %}
   {% for energy in crystal.energys.all %}
    <div class="card">
     <div class="card-content">
      <span class="card-title">
        Harnesss<span style="color: blueviolet"></span> {{ energy.wellness }} and means {{ energy.meaning}}
      </span>
    </div>
 </div>
 {% endfor %}
 {% else %}
 <h5>No Energys :(</h5>{% endif %}
</div>
<!-- Available toys will come after this line -->
</div>
<div class="col s6">
    <h3>Energys </h3>
    {% if energys.count %}
      {% for energy in energys.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              <span>{{ energy.meaning }}</span>  and <br>{{ energy.wellness }}
            </span>
          </div>
          <div class="card-action">
            <form action="{% url 'assoc_energy' crystal.id energy.id %}" method="post">
              {% csrf_token %}
              <button type="submit" class="btn">Add</button>
            </form>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>{{Crystal.name}} No More Energys to add, create more?</h5>
      <a href="/energys/create"><button type="submit" class="btn">Add More Energy</button></a>
    {% endif %}
  </div>
<script>
    let dateEl = document.getElementById('id_date');
    M.Datepicker.init(dateEl, {
        format: 'yyyy-mm-dd',
        defaultDate: new Date(),
        setDefaultDate: true,
        autoClose: true
  });
    let selectEL = document.getElementById('id_cleanse');
    M.FormSelect.init(selectEL);

  </script>  
{% endblock %}

main_app/templates/crystals/index.html
{% extends 'base.html' %}
{% block content %}

<h1> Crystal List</h1>

{% for crystal in crystals %}
<div class="card">
  <a href="{% url 'detail' crystal.id %}">
    <div class="card-content">
        <span class="card-title">{{ crystal.name }}</span>
        <p>Description: {{ crystal.description }}</p>
         <p> Color: {{crystal.color }}</p>
     </div>
    </a>
</div>
{% endfor %}


{% endblock %}

main_app/templates/home.html
{% extends 'base.html' %}

{% block content %}
<h1>Home</h1>
{% endblock %}

main_app/templates/main_app/crystal_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Crystal</h1>

  <h4>Are you sure you want to delete??</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' crystal.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/crystal_form.html
{% extends 'base.html' %}

{% block content %}
{% if object %}
<h1>Edit <span class="teal-text">{{object.name}}</span></h1>
{% else %}
<h1>Add Crystal</h1>
{% endif %}
<form action="" method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
</form>
{% endblock %}

main_app/templates/main_app/energy_confirm_delete.html
{% extends 'base.html' %}

{% block content %}

<h1>Delete Energy</h1>

<h4>Are you sure you want to delete?</h4>

<form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete" class="btn red">
    <a class="btn blue" href="{% url 'energys_detail' object.id %}">Cancel</a>
</form>

{% endblock %}

main_app/templates/main_app/energy_detail.html
{% extends 'base.html' %}

{% block content %}


<div class="card">
    <div class="card-content">
        <span class="card-title">Means<span>{{object.meaning}}</span>and harnesses{{ object.wellness }}</span>
    </div>
    <div class="card-action">
        <a href="{% url 'energys_update' object.id %}">Edit</a>
        <a href="{% url 'energys_delete' object.id %}">Delete</a>
    </div>
</div>

{% endblock %}

main_app/templates/main_app/energy_form.html
{% extends 'base.html' %}

{% block content %}

{% if object %}
    <h1>Edit </h1>
{% else %}
    <h1>Add Energy</h1>
{% endif %}


<form action="" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit" class="btn blue">
    <a class="btn red" href="{% url 'energys_index' %}">Cancel</a>
</form>

{% endblock %}

main_app/templates/main_app/energy_list.html
{% extends 'base.html' %}

{% block content %}

{% if object_list.count == 0 %}
    <h3 class="red-text">There are no Energy's entered</h3>
    <a href="{% url 'energys_create' %}">Add an Energy</a>
{% else %}
    {% for energy in object_list %}
    <div class="card">
        <a href="{% url 'energys_detail' energy.id %}">
            <div class="card-content">
                <span class="card-title">It means <span>{{energy.meaning}}</span>  and harnesses<br>{{ energy.wellness }}</span>
            </div>
        </a>
    </div>
    {% endfor %}
{% endif %}

{% endblock %}